# GISKO optimal predictions. Emits, per upcoming match, the expected-points-
# optimal scoreline + a per-round joker. Read-only; never on CI.
#
# Default: the freshly-published data/publish/world_cup/karla/predictions.json
# (regenerated by the WC forecast cron). Marginal path -- exact scoreline +
# joker (Lemma 1/2), but no p_exact and no round-total distribution.
#
# --full-posterior: re-derive from the local data/wc/fit/sim_inputs.rds cache
#   (per-draw posterior) -- adds p_exact + the round-total distribution. Only
#   as fresh as the local fit; re-run scripts/wc/forecast.R first.
# --match "A vs B @neutral #R16": explicit knockout pairing(s); uses sim_inputs.
#
# Usage:
#   Rscript scripts/wc/gisko.R
#   Rscript scripts/wc/gisko.R --full-posterior
#   Rscript scripts/wc/gisko.R --match "Spain vs France @neutral #R16"
suppressMessages(devtools::load_all(here::here()))
options(width = 120)

args <- commandArgs(trailingOnly = TRUE)
max_goals <- 8L
has_match <- any(args == "--match")
use_full <- any(args == "--full-posterior")

.round_of_match_no <- function() {
  raw <- utils::read.csv(
    here::here("data", "wc", "structure", "wc2026_schedule.csv"),
    check.names = FALSE, colClasses = "character", encoding = "UTF-8"
  )
  stats::setNames(raw[["Round Number"]], raw[["Match Number"]])
}

parse_match <- function(s) {
  rnd <- if (grepl("#", s)) trimws(sub(".*#", "", s)) else "KO"
  s2 <- sub("\\s*#.*$", "", s)
  venue <- if (grepl("@", s2)) trimws(sub(".*@\\s*", "", s2)) else "neutral"
  s3 <- sub("\\s*@.*$", "", s2)
  parts <- trimws(strsplit(s3, "\\s+vs\\s+")[[1]])
  tibble::tibble(
    home = parts[1], away = parts[2], venue = venue, round = rnd,
    label = paste(parts[1], "v", parts[2])
  )
}

write_payload <- function(payload) {
  dir.create(here::here("data", "wc", "gisko"), showWarnings = FALSE, recursive = TRUE)
  jsonlite::write_json(
    payload, here::here("data", "wc", "gisko", "optimal_picks.json"),
    auto_unbox = TRUE, pretty = TRUE, dataframe = "rows"
  )
  cli::cli_alert_success("Wrote data/wc/gisko/optimal_picks.json")
}

# ---- full-posterior path (sim_inputs.rds) ----------------------------------
run_full <- function(matches) {
  si <- readRDS(here::here("data", "wc", "fit", "sim_inputs.rds"))
  out <- lapply(split(matches, matches$round), function(mr) {
    res <- gisko_optimise_round(mr, si, max_goals = max_goals)
    res$round <- mr$round[1]
    res
  })
  for (res in out) {
    cli::cli_h2("Round {res$round}")
    tab <- res$picks
    tab$pick <- paste0(tab$opt_home, "-", tab$opt_away)
    print(tab[, c("label", "pick", "exp_points", "p_exact", "differs_from_modal")])
    cli::cli_alert_info(
      "Joker: {tab$label[res$joker]} (E[points] {round(tab$exp_points[res$joker], 2)})"
    )
    print(res$summary)
  }
  write_payload(lapply(out, function(res) {
    list(
      round = res$round, joker_label = res$picks$label[res$joker],
      picks = res$picks, summary = res$summary
    )
  }))
}

# ---- marginal path (published predictions.json) ----------------------------
run_predictions <- function() {
  pj <- jsonlite::read_json(
    here::here("data", "publish", "world_cup", "karla", "predictions.json")
  )
  if (length(pj$matches) == 0L) {
    cli::cli_alert_warning("No upcoming matches in predictions.json.")
    return(invisible())
  }
  rmap <- .round_of_match_no()
  rows <- lapply(pj$matches, function(m) {
    opt <- gisko_optimal_scoreline_marginal(
      gisko_marginals_from_predictions(m), max_goals
    )
    rnd <- unname(rmap[as.character(m$match_no)])
    tibble::tibble(
      round = ifelse(is.na(rnd), "G?", paste0("G", rnd)),
      label = paste(m$home, "v", m$away),
      pick = paste0(opt$home, "-", opt$away),
      exp_points = opt$exp_points,
      p_home = as.numeric(m$p_home), p_draw = as.numeric(m$p_draw),
      p_away = as.numeric(m$p_away),
      differs_from_modal = opt$optimal_differs_from_modal
    )
  })
  tab <- do.call(rbind, rows)
  out <- lapply(split(tab, tab$round), function(tr) {
    joker <- which.max(tr$exp_points)
    cli::cli_h2("Round {tr$round[1]}")
    print(tr[, c("label", "pick", "exp_points", "p_home", "p_draw", "p_away", "differs_from_modal")])
    cli::cli_alert_info(
      "Joker: {tr$label[joker]} (E[points] {round(tr$exp_points[joker], 2)})"
    )
    list(round = tr$round[1], joker_label = tr$label[joker], picks = tr)
  })
  cli::cli_alert_info(
    "Source: published predictions.json (marginal path). For p_exact + the round-total distribution, re-fit then run with --full-posterior."
  )
  write_payload(out)
}

if (has_match) {
  vals <- args[which(args == "--match") + 1L]
  run_full(do.call(rbind, lapply(vals, parse_match)))
} else if (use_full) {
  s <- wc_structure()
  fx <- wc_group_fixtures(s)
  up <- fx[!fx$played, , drop = FALSE]
  if (nrow(up) == 0L) {
    cli::cli_alert_warning("No upcoming group fixtures; pass --match for knockout pairings.")
    quit(status = 0L)
  }
  rmap <- .round_of_match_no()
  pk_round <- function(home, away) {
    raw <- utils::read.csv(
      here::here("data", "wc", "structure", "wc2026_schedule.csv"),
      check.names = FALSE, colClasses = "character", encoding = "UTF-8"
    )
    rk <- .wc_pair_key(
      sports:::.wc_alias(trimws(raw[["Home Team"]])),
      sports:::.wc_alias(trimws(raw[["Away Team"]]))
    )
    rn <- stats::setNames(raw[["Round Number"]], rk)
    unname(rn[.wc_pair_key(home, away)])
  }
  rn <- pk_round(up$home_team, up$away_team)
  run_full(tibble::tibble(
    home = up$home_team, away = up$away_team, venue = up$venue,
    round = ifelse(is.na(rn), "G?", paste0("G", rn)),
    label = paste(up$home_team, "v", up$away_team)
  ))
} else {
  run_predictions()
}
